"""What every card in the pool creates, and what every card is paid for.

Hand-authored from the printed text of all 151 cards. ``tools/build_card_graph.py``
turns it into ``data/cards/graph.json``; ``tests/cards/test_graph.py`` keeps the two
in step with the pool. Edit this, then re-run the builder.
"""
# Vocabulary. A token is a *mechanical state or event* one card can create and another can care
# about. Edges are produces -> rewards on the same token, so the vocabulary is the whole design:
# too coarse and everything connects to everything, too fine and real combos never meet.
TOKENS = {
 "gig.min":      "a Gig sitting at its minimum value",
 "gig.max":      "a Gig sitting at its maximum value",
 "gig.high8":    "a Gig with 8 or more value",
 "gig.pair":     "a value-pair — two Gigs showing the same value",
 "gig.distinct": "Gigs showing different values from each other",
 "gig.even":     "a Gig with an even value",
 "gig.odd":      "a Gig with an odd value",
 "gig.decrease": "pushing a Gig's value down",
 "gig.increase": "pushing a Gig's value up",
 "gig.swap":     "swapping or setting Gigs between players",
 "gig.d20":      "a d20 in the Gig area",
 "gig.d6":       "a d6 in the Gig area",
 "gig.d4":       "a d4 in the Gig area",
 "gear.equip":   "getting Gear attached to a Unit",
 "gear.equipped":"a Unit that is carrying Gear",
 "gear.stack":   "several Gear on one Unit",
 "gear.cheap":   "Gear costing 2 or less",
 "gear.cyberware":"CYBERWARE Gear specifically",
 "gear.sacrifice":"defeating your own Gear on purpose",
 "gear.tutor":   "finding Gear from the deck or trash",
 "spend.trigger":"a payoff for spending your own Unit or Legend",
 "program.play": "playing a Program",
 "program.trash":"Programs sitting in the trash",
 "program.braindance":"BRAINDANCE Programs",
 "program.discard":"discarding Programs as a cost",
 "legend.call_free":"Calling a Legend for free",
 "legend.faceup":"friendly face-up Legends",
 "legend.go_solo":"GO SOLO — playing a Legend as a Unit",
 "legend.ready": "readying Legends",
 "trash.self":   "putting your own cards into the trash",
 "trash.recur":  "playing or returning cards from the trash",
 "unit.ready":   "readying a Unit for another attack",
 "unit.spend_rival":"spending a rival Unit",
 "unit.defeat_rival":"defeating a rival Unit",
 "unit.power_zero":"a Unit with 0 power",
 "unit.adrenaline":"attacking the turn a Unit is played",
 "blocker":      "BLOCKER",
 "power.pump":   "giving a Unit more power for the turn",
 "power.threshold":"crossing a 10-power step for an extra stolen Gig",
 "draw":         "drawing cards",
 "discard.rival":"making a Rival discard",
 "eddie.ready":  "readying Eddies — extra money this turn",
 "cost.reduce":  "paying less for a card",
 "play.free":    "playing something for free",
 "cred.more":    "having MORE Street Cred than a Rival",
 "cred.less":    "having LESS Street Cred than a Rival",
 "cred.even":    "Street Cred being an even number",
 "behind.gigs":  "a Rival being 2+ Gigs ahead of you",
}

# p = produces / enables, r = rewards / needs, arch = archetype clusters
C = {}

# ---------------------------------------------------------------- Gear
C.update({
"kiroshi-optics":        {"p":["gear.equip","gear.cheap","gear.cyberware"],"r":["legend.faceup"],"arch":["gear"]},
"mandibular-upgrade":    {"p":["gear.equip","gear.cheap","gear.cyberware","blocker"],"r":[],"arch":["gear","defense"]},
"mantis-blades":         {"p":["gear.equip","gear.cheap","gear.cyberware"],"r":[],"arch":["gear"]},
"tetratronic-rippler":   {"p":["gear.equip","gear.cheap","gear.cyberware","trash.self"],"r":["spend.trigger"],"arch":["gear","engine"]},
"adrenaline-converter":  {"p":["gear.equip","gear.cheap","gear.cyberware","unit.adrenaline"],"r":["behind.gigs"],"arch":["gear","comeback"]},
"arasaka-emergency-radioport":{"p":["gear.equip","gear.cheap","gear.cyberware","legend.call_free"],"r":["spend.trigger","legend.go_solo"],"arch":["gear","arasaka","legends"]},
"dying-night-vs-pistol": {"p":["gear.equip","gear.cheap","gig.decrease","gig.min","eddie.ready"],"r":[],"arch":["gear","gig-control"]},
"riot-shield":           {"p":["gear.equip","gear.cheap","blocker"],"r":[],"arch":["gear","defense"]},
"satori-sword-of-saburo":{"p":["gear.equip","gear.cheap","draw"],"r":[],"arch":["gear","arasaka"]},
"zetatech-faceplate":    {"p":["gear.equip","gear.cheap","gear.cyberware","draw"],"r":["spend.trigger","gig.distinct"],"arch":["gear","engine"]},
"deadman-transmitter":   {"p":["gear.equip","gear.cyberware"],"r":[],"arch":["gear","defense"]},
"netwatch-netdriver":    {"p":["gear.equip","gear.cyberware","draw"],"r":["spend.trigger"],"arch":["gear","engine"]},
"sandevistan":           {"p":["gear.equip","gear.cyberware","unit.ready"],"r":[],"arch":["gear","engine"]},
"gorilla-arms":          {"p":["gear.equip","gear.cyberware"],"r":["gig.distinct"],"arch":["gear","aggro"]},
"overwatch-panams-gift": {"p":["gear.equip","unit.defeat_rival"],"r":[],"arch":["gear","removal"]},
"the-relic-experimental-biochip":{"p":["gear.equip","gear.cyberware","trash.recur","play.free"],"r":[],"arch":["gear","arasaka","recursion"]},
"zetatech-berserk":      {"p":["gear.equip","gear.cyberware"],"r":["legend.faceup","cost.reduce"],"arch":["gear","legends"]},
})

# ---------------------------------------------------------------- Legends
C.update({
"alt-cunningham-soulkiller-architect":{"p":["cost.reduce","trash.recur","program.play"],"r":["gig.min","program.trash"],"arch":["programs","engine"]},
"evelyn-parker-beautiful-enigma":{"p":["eddie.ready"],"r":[],"arch":["tempo"]},
"jackie-welles-pour-one-out-for-me":{"p":["gig.decrease","gig.min","draw"],"r":["gear.equip"],"arch":["gig-control","blue"]},
"judy-alvarez-braindance-maestro":{"p":["power.pump","trash.self","draw"],"r":["program.braindance","program.play"],"arch":["programs","braindance"]},
"sasha-yakovleva-wont-let-you-down":{"p":["legend.go_solo","draw","discard.rival","power.pump"],"r":[],"arch":["legends"]},
"v-corporate-exile":{"p":["legend.go_solo"],"r":["power.threshold"],"arch":["legends","aggro"]},
"wakako-okada-peace-and-harmony":{"p":["gig.decrease","draw","power.pump"],"r":[],"arch":["utility"]},
"goro-takemura-hands-unclean":{"p":["legend.go_solo","blocker"],"r":[],"arch":["legends","defense"]},
"goro-takemura-vengeful-bodyguard":{"p":["blocker","power.pump","draw","trash.self"],"r":["gig.pair","blocker"],"arch":["defense","gig-control"]},
"hanako-arasaka-daughter-of-the-emperor":{"p":["gig.swap","draw"],"r":["gig.pair"],"arch":["gig-control","arasaka"]},
"jackie-welles-mamas-favorite":{"p":["legend.go_solo"],"r":[],"arch":["legends","defense"]},
"padre-man-of-the-cross":{"p":["unit.spend_rival","draw","gig.swap","gig.pair"],"r":[],"arch":["utility","gig-control"]},
"panam-palmer-nomad-cavalry":{"p":["unit.ready","legend.ready"],"r":["gear.equip","gear.equipped"],"arch":["gear","engine"]},
"saburo-arasaka-stubborn-patriarch":{"p":["power.pump","power.threshold"],"r":[],"arch":["arasaka","aggro"]},
"adam-smasher-ender-of-legends":{"p":["legend.go_solo","unit.defeat_rival"],"r":["power.threshold"],"arch":["legends","removal","topend"]},
"dexter-deshawn-off-the-grid":{"p":["power.pump","draw","gig.increase","gig.high8"],"r":[],"arch":["utility"]},
"johnny-silverhand-rocking-renegade":{"p":["power.pump","unit.adrenaline"],"r":["gig.high8","cost.reduce"],"arch":["aggro","rocker"]},
"rebecca-having-a-moment":{"p":[],"r":[],"arch":[]},
"royce-psycho-on-the-edge":{"p":["legend.go_solo"],"r":["gear.equip","gear.stack","gear.equipped","power.threshold"],"arch":["gear","legends"]},
"v-streetkid":{"p":["legend.go_solo","trash.self","trash.recur"],"r":["program.braindance","program.trash"],"arch":["braindance","legends"]},
"yorinobu-arasaka-embracing-destruction":{"p":["draw"],"r":["cred.more"],"arch":["arasaka","engine"]},
"dum-dum-maelstrom-triggerman":{"p":["draw","gear.sacrifice","power.pump"],"r":["gear.equip","gear.stack","gear.equipped"],"arch":["gear","maelstrom"]},
"kerry-eurodyne-axe-attitude-audience":{"p":["draw"],"r":["gig.min","gig.max","gig.d20"],"arch":["dice","engine"]},
"muamar-reyes-el-capitan":{"p":["draw","gig.increase","gig.decrease","gig.pair"],"r":[],"arch":["utility","gig-control"]},
"river-ward-detective-on-the-hunt":{"p":["gear.equip","play.free","trash.self"],"r":["gear.cheap","gear.equipped"],"arch":["gear","engine"]},
"rogue-amendiares-preem-solo":{"p":["legend.go_solo","draw","discard.rival"],"r":["gig.even","gig.odd"],"arch":["legends"]},
"viktor-vektor-sit-down-and-relax":{"p":["gear.tutor"],"r":["gear.cheap"],"arch":["gear"]},
})

# ---------------------------------------------------------------- Programs
C.update({
"afterparty-at-lizzies":{"p":["program.play","program.braindance","draw"],"r":["gig.distinct"],"arch":["braindance","gig-control"]},
"all-is-lost":{"p":["program.play","trash.self"],"r":[],"arch":["programs"]},
"detonate":{"p":["program.play"],"r":[],"arch":["programs","removal"]},
"floor-it":{"p":["program.play","power.pump","draw"],"r":[],"arch":["programs"]},
"industrial-assembly":{"p":["program.play","program.braindance","gig.increase","gig.high8","draw"],"r":["gig.high8"],"arch":["braindance","gig-control","arasaka"]},
"peace-offering":{"p":["program.play","program.braindance","gig.swap","gig.pair","draw"],"r":["gig.pair"],"arch":["braindance","gig-control"]},
"synapse-burnout":{"p":["program.play","power.pump"],"r":["legend.faceup"],"arch":["programs","legends"]},
"trust-no-one":{"p":["program.play","program.braindance","gig.decrease","gig.min","draw"],"r":["gig.min"],"arch":["braindance","gig-control"]},
"corporate-surveillance":{"p":["program.play","unit.spend_rival"],"r":[],"arch":["programs","corpo"]},
"fool-on-the-hill":{"p":["program.play","draw","trash.self"],"r":[],"arch":["programs"]},
"reboot-optics":{"p":["program.play"],"r":[],"arch":["programs","defense"]},
"safety-override":{"p":["program.play","unit.defeat_rival"],"r":[],"arch":["programs","removal"]},
"take-control":{"p":["program.play","draw"],"r":[],"arch":["programs","defense"]},
"the-heist":{"p":["program.play","trash.self","gear.tutor","play.free"],"r":["gear.cheap"],"arch":["gear","programs"]},
"three-mouths-one-desire":{"p":["program.play","program.braindance","draw"],"r":["gig.min"],"arch":["braindance","gig-control"]},
"appetite-for-destruction":{"p":["program.play"],"r":["power.pump"],"arch":["programs","aggro"]},
"bonnie-and-clyde":{"p":["program.play","program.braindance","unit.defeat_rival"],"r":["behind.gigs"],"arch":["braindance","removal","comeback"]},
"chrome-reverie":{"p":["program.play","program.braindance","legend.call_free"],"r":["gig.min"],"arch":["braindance","legends"]},
"cyberpsychosis":{"p":["program.play","power.pump","power.threshold"],"r":["gear.equip","gear.stack","gear.equipped"],"arch":["gear","programs"]},
"live-with-the-aftermath":{"p":["program.play","unit.defeat_rival","trash.self"],"r":[],"arch":["programs","removal"]},
"nocturne-op55n1":{"p":["program.play","draw","cost.reduce"],"r":["legend.go_solo"],"arch":["programs","legends","arasaka"]},
"over-the-edge":{"p":["program.play","unit.defeat_rival"],"r":["gig.d20"],"arch":["programs","removal","dice"]},
"pyramid-song":{"p":["program.play","program.braindance","power.pump"],"r":["gig.min","gig.d4","unit.power_zero"],"arch":["braindance","removal"]},
"gunpoint-diplomacy":{"p":["program.play","power.pump"],"r":["cred.more"],"arch":["programs","aggro"]},
"memory-relapse":{"p":["program.play","program.braindance","unit.spend_rival","draw"],"r":["cred.even"],"arch":["braindance","tempo"]},
"shattered-memories":{"p":["program.play","program.braindance","draw","trash.self"],"r":[],"arch":["braindance"]},
"unlikely-bond":{"p":["program.play"],"r":[],"arch":["programs","tempo"]},
"bootleg-black-sapphire-show":{"p":["program.play","program.braindance","draw","eddie.ready"],"r":["gig.even","gig.odd","gig.distinct"],"arch":["braindance","gig-control"]},
"les-elemens":{"p":["program.play"],"r":[],"arch":["programs","removal","corpo"]},
"we-gotta-live-together":{"p":["program.play","trash.recur","play.free","cost.reduce"],"r":["behind.gigs"],"arch":["programs","recursion","comeback"]},
"wild-in-the-streets":{"p":["program.play","unit.defeat_rival"],"r":[],"arch":["programs","removal"]},
"carnage-at-the-colosseum":{"p":["program.play","program.braindance","unit.defeat_rival","cost.reduce"],"r":["gig.high8"],"arch":["braindance","removal","gig-control"]},
"towerfall":{"p":["program.play","program.braindance","power.pump"],"r":["cred.less","unit.power_zero"],"arch":["braindance","removal","comeback"]},
"dont-fear-the-reaper":{"p":["program.play","unit.spend_rival","unit.defeat_rival"],"r":[],"arch":["programs","removal","topend"]},
})

# ---------------------------------------------------------------- Units
C.update({
"corpo-security":{"p":["blocker"],"r":[],"arch":["defense","corpo"]},
"evelyn-parker-scheming-siren":{"p":["draw","unit.power_zero","trash.self"],"r":["cred.more"],"arch":["engine"]},
"jacked-in-voodoo-boy":{"p":[],"r":["program.play"],"arch":["programs"]},
"japantown-jonin":{"p":["power.pump","unit.power_zero","power.threshold"],"r":[],"arch":["aggro"]},
"ruthless-lowlife":{"p":[],"r":[],"arch":["aggro"]},
"secondhand-bombus":{"p":["blocker","unit.power_zero"],"r":[],"arch":["defense"]},
"sketchy-ripper":{"p":["gear.tutor","unit.power_zero"],"r":["gear.cheap"],"arch":["gear"]},
"tygers-whisper":{"p":["legend.call_free","unit.power_zero"],"r":["legend.go_solo"],"arch":["legends"]},
"augmented-negotiators":{"p":["blocker","discard.rival"],"r":[],"arch":["defense","arasaka"]},
"delamain-rideshare-ai":{"p":["draw","unit.power_zero"],"r":[],"arch":["value"]},
"dexter-deshawn-one-last-chance":{"p":["gig.increase","gig.decrease","draw"],"r":["cred.more","cred.less"],"arch":["gig-control"]},
"emergency-atlus":{"p":[],"r":[],"arch":["aggro"]},
"field-operator":{"p":["draw"],"r":["cred.even"],"arch":["arasaka","value"]},
"la-llorona-ghost-of-the-past":{"p":["blocker","gig.increase","gig.high8"],"r":[],"arch":["defense","gig-control"]},
"maelstrom-goons":{"p":["discard.rival"],"r":["gear.equip","gear.equipped"],"arch":["gear","maelstrom"]},
"maxtac-squadron":{"p":["legend.ready"],"r":["spend.trigger","legend.faceup"],"arch":["legends","engine"]},
"misty-olszewski-mender-of-broken-spirits":{"p":["draw","eddie.ready","unit.power_zero","trash.self"],"r":[],"arch":["engine","value"]},
"mox-inciters":{"p":["blocker"],"r":[],"arch":["defense"]},
"swordwise-huscle":{"p":["draw"],"r":["power.pump","gear.equip"],"arch":["value"]},
"valentino-guerrera":{"p":[],"r":["cred.more"],"arch":["aggro"]},
"valentino-street-racer":{"p":["unit.adrenaline"],"r":[],"arch":["aggro","tempo"]},
"viktor-vektor-you-might-feel-a-little-pinch":{"p":["gear.equip","trash.recur","play.free","gear.cyberware"],"r":["gear.cheap","trash.self"],"arch":["gear","recursion"]},
"6th-street-recruits":{"p":["gig.increase","gig.high8"],"r":["gig.d6"],"arch":["gig-control","dice"]},
"delamain-cab":{"p":["eddie.ready"],"r":[],"arch":["tempo"]},
"gilded-maton":{"p":["gear.sacrifice","unit.defeat_rival"],"r":["gear.equip"],"arch":["gear","removal"]},
"goro-takemura-losing-his-way":{"p":["power.pump","power.threshold"],"r":["legend.faceup"],"arch":["arasaka","legends"]},
"hacked-corpo":{"p":["trash.self"],"r":["program.trash"],"arch":["programs"]},
"hanako-arasaka-in-a-gilded-cage":{"p":["draw"],"r":["gig.distinct"],"arch":["arasaka","gig-control"]},
"kerry-eurodyne-the-last-rockerboy":{"p":["draw"],"r":["gig.high8"],"arch":["rocker","gig-control"]},
"maelstrom-zealots":{"p":["unit.defeat_rival","unit.power_zero"],"r":[],"arch":["defense","maelstrom"]},
"meredith-stout-stone-cold-corpo":{"p":["blocker","trash.recur"],"r":["gig.swap","legend.go_solo"],"arch":["corpo","defense"]},
"offduty-malfini":{"p":["unit.spend_rival"],"r":[],"arch":["tempo"]},
"pacifica-netrunner":{"p":[],"r":["cred.even"],"arch":["tempo"]},
"pepe-najarro-working-doubles":{"p":["legend.ready"],"r":["gig.pair"],"arch":["legends","gig-control"]},
"psycho-squad":{"p":[],"r":[],"arch":["aggro"]},
"rita-wheeler-no-stupid-questions":{"p":["blocker","draw","trash.self"],"r":["spend.trigger"],"arch":["defense","engine"]},
"t-bug-amateur-philosopher":{"p":["legend.call_free"],"r":["legend.go_solo"],"arch":["legends"]},
"westbrook-netrunner":{"p":[],"r":[],"arch":["defense"]},
"caliber-totentanzs-top-dog":{"p":["unit.defeat_rival","discard.rival"],"r":[],"arch":["removal","maelstrom"]},
"chrome-fang":{"p":[],"r":[],"arch":["defense"]},
"el-sombreron-la-venganza-lenta":{"p":["power.pump","power.threshold"],"r":["gig.max","gig.increase"],"arch":["gig-control","aggro"]},
"lizzy-wizzy-delicate-weapon":{"p":["program.play","play.free","trash.recur","blocker"],"r":["program.trash"],"arch":["programs","rocker"]},
"mtod12-flathead":{"p":[],"r":["cred.less"],"arch":["aggro","comeback"]},
"maman-brigitte-spirit-of-death":{"p":["program.discard","trash.self"],"r":["program.trash"],"arch":["programs","removal"]},
"maxtac-av":{"p":["gig.swap"],"r":[],"arch":["gig-control","aggro"]},
"maxtac-suppression-team":{"p":[],"r":[],"arch":["defense"]},
"modded-muramasa":{"p":["unit.ready"],"r":["cred.less"],"arch":["comeback","tempo"]},
"riding-nomad":{"p":["unit.adrenaline"],"r":[],"arch":["aggro","nomad"]},
"rockn-rockerboy":{"p":[],"r":[],"arch":["aggro","rocker"]},
"rogue-amendiares-queen-of-the-afterlife":{"p":["eddie.ready","power.pump"],"r":[],"arch":["tempo"]},
"royce-dont-call-me-simon":{"p":["unit.defeat_rival"],"r":["cred.more"],"arch":["removal","maelstrom"]},
"screw-lovelorn-fool":{"p":["trash.recur"],"r":["trash.self"],"arch":["recursion","maelstrom"]},
"v-roamer-of-the-badlands":{"p":["gig.increase","gig.high8","draw"],"r":["gig.high8"],"arch":["gig-control","nomad"]},
"viktor-vektor-drop-your-illusions":{"p":["cost.reduce"],"r":["gear.cyberware","gear.equip"],"arch":["gear"]},
"wraith-marauders":{"p":["unit.ready"],"r":[],"arch":["nomad","tempo"]},
"animals-wrecker":{"p":["power.threshold"],"r":[],"arch":["aggro","topend"]},
"heywood-ripperdoc":{"p":["gear.sacrifice","draw"],"r":["gear.equip"],"arch":["gear","removal"]},
"jackie-welles-ride-or-die-choom":{"p":["power.pump","draw","power.threshold"],"r":["gig.even","gig.odd"],"arch":["gig-control","aggro"]},
"johnny-silverhand-never-stop-fighting":{"p":["unit.ready"],"r":[],"arch":["aggro","rocker"]},
"judy-alvarez-nothing-to-doubt":{"p":["draw","play.free"],"r":[],"arch":["value","engine"]},
"modded-kusanagi":{"p":["unit.adrenaline"],"r":[],"arch":["aggro","tempo"]},
"nadia-fighting-through-grief":{"p":["unit.adrenaline"],"r":["behind.gigs"],"arch":["comeback","aggro"]},
"panam-palmer-strength-through-family":{"p":["legend.call_free","draw","trash.self"],"r":["legend.faceup","legend.go_solo"],"arch":["legends","nomad"]},
"trauma-team-operatives":{"p":["cost.reduce"],"r":["trash.self"],"arch":["value"]},
"alt-cunningham-mother-of-daemons":{"p":["draw"],"r":["gear.equip","gear.equipped","spend.trigger"],"arch":["gear","engine","defense"]},
"maxtac-heavy":{"p":["cost.reduce"],"r":[],"arch":["topend"]},
"minotaur":{"p":["unit.defeat_rival","power.threshold"],"r":["cred.more"],"arch":["arasaka","removal","topend"]},
"octant":{"p":["cost.reduce"],"r":["gig.high8"],"arch":["gig-control","topend"]},
"sandayu-oda-hanakos-guardian":{"p":["unit.spend_rival"],"r":["gig.pair"],"arch":["arasaka","gig-control","topend"]},
"yorinobu-arasaka-steel-dragon":{"p":["play.free","trash.recur","draw","power.threshold"],"r":[],"arch":["arasaka","topend","recursion"]},
"placide-voodoo-sentinel":{"p":["program.discard","power.threshold"],"r":["program.trash"],"arch":["programs","removal","topend"]},
"saul-bright-stormrider":{"p":["power.pump","unit.ready","power.threshold"],"r":[],"arch":["nomad","aggro","topend"]},
"adam-smasher-metal-over-meat":{"p":["unit.defeat_rival","power.threshold"],"r":[],"arch":["removal","topend"]},
})
